name: 6.fcooper_load_voxelNet_det_multi_mmd_shift_based_PGD_all #AdvGRL_v2xvit
save_path: /home/jinlongli/2.model_saved/3.Attack_V2V2023
root_dir: /home/jinlongli/opv2v_data_dumping/train # /home/jinlongli/opv2v_data_dumping/train
root_dir_target: /home/jinlongli/opv2v_data_dumping/train  #/home/jinlongli/V2V4Real/train  #/home/jinlongli/V2V4Real/train
validate_dir: /home/jinlongli/personal/DATASet/opv2v_data_dumping/test_culver_city

# wild_setting:
#   async: false
#   async_overhead: 100
#   seed: 20
#   loc_err: false
#   xyz_std: 0.2
#   ryp_std: 0.2
#   data_size: 1.06 # Mb!!
#   transmission_speed: 27 # Mbps!!
#   backbone_delay: 10 # ms

Attack_params:
  attacked_pose_save: False
  npy_save: false
  random: False
  num_iter_per: 10
  pose_x:
      use: &x True
      value: &x_value 1.118
  pose_y:
      use: &y True
      value: &y_value 1.118
  pose_z:
      use: &z False
      value: &z_value 1.395
  pose_roll:
      use: &roll False
      value: &roll_value 0.141
  pose_yaw:
      use: &yaw False
      value: &yaw_value 0.141
  pose_pitch:
      use: &pitch False
      value: &pitch_value 0.141
  pose_use: [*x,*y,*z,*roll,*yaw,*pitch]
  pose_value: [*x_value,*y_value,*z_value,*roll_value,*yaw_value,*pitch_value]


yaml_parser: "load_point_pillar_params"
train_params:
  DA_trianing:  GRL   #1)GRL  2)ADDA 
  batch_size: &batch_size 4
  epoches: &epoches 60
  eval_freq: 1
  save_freq: 1
  max_cav: &max_cav 5

fusion:
  core_method: 'IntermediateFusionDataset' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args: []

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'VoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 8]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  # lidar range for each individual cav.
  cav_lidar_range: &cav_lidar [-140.8, -38.4, -5, 140.8, 38.4, 3]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 4
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# model related
model:
  core_method: point_pillar_fcooper
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    compression: 0 # compression rate
    backbone_fix: false

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
    shrink_header:
      kernal_size: [3]
      stride: [2]
      padding: [1]
      dim: [256]
      input_dim: 384 # 128 * 3
    ####DA  component########
    AdvGRL: true # False
    advGRL_threshold: 30.0
    DA_feature_head: 256
    DA_instance_head: 88
    DA_feature_weight: 0.1
    DA_instance_weight: 0.1
    grl_feature_weight: 0.1
    grl_instance_weight: 0.1
      # add decoder later

      # add decoder later

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 0.0002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
    core_method: cosineannealwarm #step, multistep, Exponential and cosineannealwarm support
    epoches: *epoches
    warmup_lr: 2e-4
    warmup_epoches: 10
    lr_min: 2e-5

